### PR TITLE
Fix issues identified by cppcheck

### LINKED ISSUE #899: Usless assigments to argument
In these places:
https://github.com/llnl/sundials/blob/178eae817c7a5338e5f572d3a62d8cb6b4728fce/src/sundials/sundials_direct.c#L182
https://github.com/llnl/sundials/blob/178eae817c7a5338e5f572d3a62d8cb6b4728fce/src/sundials/sundials_direct.c#L260
https://github.com/llnl/sundials/blob/178eae817c7a5338e5f572d3a62d8cb6b4728fce/src/sundials/sundials_direct.c#L266
https://github.com/llnl/sundials/blob/178eae817c7a5338e5f572d3a62d8cb6b4728fce/src/sundials/sundials_nvector.c#L1080
`NULL` is assigned to a local copy of the pointer - this assignment has no effect for the caller (cf. [example at godbolt](https://godbolt.org/z/4Tda4Y5xM)).

### PR DESCRIPTION
**Pull request by Steven-Roberts**
cppcheck flagged a few memory leaks in the unlikely case of a malloc failing in a constructor, and codex did a decent job at fixing them. These fixes aren't so important, but they make the cppcheck report shorter so it will be easier to identify more important issues in the future.

### CODE REVIEW

File: src/kinsol/kinsol.c
Comment (drreynolds) [inline src/kinsol/kinsol.c:1]: I don't quite understand the changes in this file -- is it that the KIN_PROFILER lives inside `kin_mem`, and so we cannot mark the function end after freeing?

**Review by drreynolds — COMMENTED** [review]
Aside from my one question below, this LGTM

File: src/kinsol/kinsol.c
Comment (Steven-Roberts) [reply src/kinsol/kinsol.c:1]: Yes, exactly 
https://github.com/llnl/sundials/blob/0a1024b7fb902a5eae3142adf8c13561c6989543/src/kinsol/kinsol_impl.h#L59

**Review by balos1 — DISMISSED** [review]

File: src/cvodes/cvodea.c [hunk 1]
```diff
@@ -692,21 +692,21 @@ int CVodeCreateB(void* cvode_mem, int lmmB, int* which)
...
   }
 
-  /* Create and set a new CVODES object for the backward problem */
+  /* Allocate space for new CVodeBMem object */
 
-  cvodeB_mem = CVodeCreate(lmmB, cv_mem->cv_sunctx);
-  if (cvodeB_mem == NULL)
+  new_cvB_mem = NULL;
+  new_cvB_mem = (CVodeBMem)malloc(sizeof(struct CVodeBMemRec));
+  if (new_cvB_mem == NULL)
```
Comment (gardner48) [inline src/cvodes/cvodea.c]: Switching the ordering creates a different potential leak. If the `malloc` fails, we should call `CVodeFree` on `cvodeB_mem` below. I think we should keep the original ordering (create `new_cvB_mem` first since we'll attach other objects to it) and add `free(new_cvB_mem)` if `CVodeCreate` fails.

File: src/idas/idaa.c [hunk 2]
```diff
@@ -682,18 +682,18 @@ int IDACreateB(void* ida_mem, int* which)
...
                     MSG_MEM_FAIL);
     return (IDA_MEM_FAIL);
   }
 
-  /* Allocate the IDAMem struct needed by this backward problem. */
-  ida_memB = IDACreate(IDA_mem->ida_sunctx);
-  if (ida_memB == NULL)
+  /* Allocate a new IDABMem struct. */
+  new_IDAB_mem = (IDABMem)malloc(sizeof(struct IDABMemRec));
+  if (new_IDAB_mem == NULL)
```
Comment (gardner48) [inline src/idas/idaa.c]: Same comment as in CVODES

**Review by gardner48 — CHANGES_REQUESTED** [review]

**Comment by gardner48** [comment]
Also note in the change log / recent changes that potential memory leaks were fixed if a memory allocation fails.

**Review by gardner48 — APPROVED** [review]
